name: Manual Dependabot Trigger
on:
  workflow_dispatch:
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Dependabot
        uses: dependabot/dependabot-core@v0.141.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
